### ISSUE TITLE
dataset CSV files

### ISSUE THREAD

**Issue by maysoonalfares** [rafalposwiata/depression-detection-lt-edi-2022#3]
I need the csv files please to download them 
may20228092@std.psut.edu.jo

**Comment by rafalposwiata** [comment]
Hi, dataset is in tsv format in the [/data](https://github.com/rafalposwiata/depression-detection-lt-edi-2022/tree/main/data) folder. I don't prepare files in other formats.

**Comment by maysoonalfares** [comment]
I mean the data files under (processed data) folder, they are in csv but I can't view them

**Comment by rafalposwiata** [comment]
ok, I thought you meant the [original dataset.](https://github.com/rafalposwiata/depression-detection-lt-edi-2022/tree/main/data/original_dataset) Files from the [preprocessed_dataset ](https://github.com/rafalposwiata/depression-detection-lt-edi-2022/tree/main/data/preprocessed_dataset) folder may not display in the browser because they are too big, but you can download them.

![image](https://github.com/rafalposwiata/depression-detection-lt-edi-2022/assets/22004654/9c44cb3a-aec3-4428-842d-d8e9006a7091)

**Comment by maysoonalfares** [comment]
Thank you sir
